[package]
name = "fundamentals-derive"
version = "0.0.1-alpha.1"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
kproc-parser = { version = "0.0.1-beta.5", features = ["proc_macro_wrapper"] }
