[package]
name = "lnspec_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
kproc-parser = { git = "https://github.com/vincenzopalazzo/kproc-macros.git", features = ["proc_macro_wrapper"] }
